name: jobcard_tracker
description: Job Card Tracker Application
publish_to: 'none'
version: 1.2.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  http: ^1.2.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  shared_preferences: ^2.3.2
  flutter_foreground_task: ^8.14.0
  web: ^1.0.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  file_picker: ^11.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/